# Generated by Django 5.1.3 on 2024-12-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('nombre_comun', models.CharField(max_length=100)),
                ('tipo_de_clima', models.CharField(max_length=30)),
                ('riego_semanal', models.IntegerField()),
                ('ciudados_especiales', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('nombre_comun', models.CharField(max_length=100)),
                ('tipo_de_luz', models.CharField(max_length=15)),
                ('riego_semanal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nombre_usuario', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
