# Generated by Django 5.1.3 on 2024-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interior',
            name='foto',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
